#todo: ie handling initialization for local dev. building the app with the container might still be useful?

services:
  api:
    build:
      context: ./backend/inflation-feed.Api
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__Default=Server=database;Database=InflationDb;User=sa;Password=YourStrong!Passw0rd
    depends_on:
      - database

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql
    mem_limit: 4g

  frontend:
    working_dir: /app
    image: node:18-alpine
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./frontend:/app
    depends_on:
      - api

volumes:
  sqlserver_data: