version: "3.8"

services:
  api:
    build:
      context: ./backend/InflationFeed.Api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=InflationDb;Username=postgres;Password=YourStrongPassword
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:15-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: InflationDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YourStrongPassword
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api

volumes:
  pg_data: