version: "3.8"
#straight up idk if this is necessary i think i'm making sqlite too complicated
#todo: figure out how people are using sqlite in docker typically
#todo: ie handling initialization for local dev. building the app with the container might still be useful?
services:
  api:
    build:
      context: ./backend/inflation-feed.Api
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - db
    volumes:
      - ./db:/data

  db:
    image: alpine:latest
    volumes:
      - ./db:/data
    entrypoint: /bin/sh -c "apk add --no-cache sqlite && sqlite3 /data/inflation-feed.db < /data/init.sql"

  frontend:
    working_dir: /app
    image: node:18-alpine
    ports:
      - "3000:5173"
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./frontend:/app
    depends_on:
      - api
