version: "3.8"

services:
  api:
    build:
      context: ./backend/InflationFeed.Api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=InflationDb;Username=postgres;Password=YourStrongPassword
    depends_on:
      - database

  database:
    image: postgres:15-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: InflationDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YourStrongPassword
    volumes:
      - pg_data:/var/lib/postgresql/data

  frontend:
    working_dir: /app
    image: node:18-alpine
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./frontend:/app
    depends_on:
      - api

volumes:
  pg_data: