CREATE TABLE IF NOT EXISTS Prices (
    Id INTEGER PRIMARY KEY,
    Sku TEXT NOT NULL,
    Store TEXT NOT NULL,
    Amount DECIMAL(10, 2) NOT NULL,
    Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO Prices (Sku, Store, Amount) VALUES 
('SKU123', 'StoreA', 4.99),
('SKU123', 'StoreB', 5.29),
('SKU456', 'StoreA', 2.99);